### PR TITLE
Allow fields_for-like attributes

### PR DESCRIPTION
**Pull request by daniel-rikowski**
This is the same as #75, including the changes you asked for.

(I don't know how to rebase a pull request on the Github web interface, so creating a new one was the fastest solution for me)

### CODE REVIEW

**Comment by daniel-rikowski** [comment]
Any news on this? Can this be merged or are there still issues to address?

**Comment by clemens** [comment]
Any idea why 2 of the test runs are failing? Other than that, I'm good to merge it.

**Comment by daniel-rikowski** [comment]
I can see only *one* failing test... (https://travis-ci.org/clemens/delocalize/jobs/48057279)

It looks like a Travis CI cannot find the minitest gem. Newer versions of ActiveSupport have an explicit dependency on minitest, which Rails 3.2 didn't have. 
Also Ruby 2.2 no longer ships all minitest/testunit files (https://bugs.ruby-lang.org/issues/10746) But as long as there is a minitest gem installed - via gemfile or perhaps by a previous test - there is no problem.

I'd guess that adding minitest as an explicit dependency for Ruby 2.2+ should fix the problem.

**Comment by clemens** [comment]
There's another test run that didn't start at all – which I considered a test with error as well. :)

**Comment by daniel-rikowski** [comment]
Ah, sorry, I just look for the color red :eyeglasses: 

Just guessing here: The sqlite3 version is incompatible with Rubinius (Seems to happen: https://github.com/travis-ci/travis-ci/issues/2006) Perhaps pinning down the version of sqlite3 to an earlier version could help here, too.

**Comment by clemens** [comment]
I've just downgraded to 1.3.8 for Rubinius only. I'll have a look what the build says. Then I'll have a look at the other issue.

**Comment by clemens** [comment]
Just as a heads up: Now the build is failing on 2.2.0 (sqlite3 1.3.8 doesn't build) which I can't reproduce locally (it builds just fine). I'll have to have another look but I might just merge it because it looks fine locally.

Sorry it's taking so long with those god damn incompatibilities. But I hate merging broken builds for reasons I'm sure you can understand. :)

**Comment by clemens** [comment]
I'll just merge it. I hope noone uses sqlite in production. ;-) And if they do and they have issues, the can submit an issue/PR.

Thanks for the contribution and your patience, man!

**Pull request merged**
